version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - run: export COMMIT_MESSAGE=\"$(git log --format=%B -n 1 $CIRCLE_SHA1)\" >> ~/.bashrc
      - run: echo $COMMIT_MESSAGE
workflows:
    build-and-test:
      jobs:
        - build-and-test
