version: 2.1
orbs:
  node: circleci/node@1.1.6
commands:
  create-env-vars:
    description: "Create en vars"
    steps:
      - run: 
          name: "Setup custom environment variables"
          command: echo 'export MY_ENV_VAR="$(git log --format=%B -n 1 $CIRCLE_SHA1)"' >> $BASH_ENV
  notify-google-chat:
    description: "Notify google chat"
    parameters:
      notify_success:
        default: false
        type: boolean
    steps:
      - run:
          name: Set GIT_COMMIT_MESSAGE
          when: always
          command: echo 'export MY_ENV_VAR="$(git log --format=%B -n 1 $CIRCLE_SHA1)"' >> $BASH_ENV
      - run:
          name: Notify google chat on fail
          when: on_fail
          command: echo Failed $MY_ENV_VAR
      - run:
          name: Notify google chat on success
          when: on_success
          command: echo "Success"

jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
      - run: 
          name: "What was my custom environment variable?"
          command: echo ${MY_ENV_VAR}
      - notify-google-chat:
          notify_success: true
  second-job:
    executor:
      name: node/default            
    steps:
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
      - notify-google-chat
      - run: 
          name: "What was my custom environment variable?"
          command: |
            echo ${MY_ENV_VAR}
  third-job:
    executor:
      name: node/default            
    steps:
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
      - run: 
          name: "What was my custom environment variable?"
          command: notify-success
      - notify-google-chat
workflows:
    build-and-test:
      jobs:
        - build-and-test
        - second-job:
            requires:
              - build-and-test
        - third-job:
            requires:
              - build-and-test
