version: 2.1
orbs:
  node: circleci/node@1.1.6
commands:
  create-env-vars:
    description: "Create en vars"
    steps:
      - run: 
          name: "Setup custom environment variables"
          command: echo 'export MY_ENV_VAR="$(git log --format=%B -n 1 $CIRCLE_SHA1)"' >> $BASH_ENV
  notify-google-chat:
    description: "Notify google chat"
    steps:
      - run:
          name: Notify google chat on success
          when: on_success
          command: >
            echo Success
      - run:
          name: Notify google chat on fail
          when: on_success
          command: >
            echo Failed
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - create-env-vars
      - run: 
          name: "What was my custom environment variable?"
          command: echo ${MY_ENV_VAR}
      - notify-google-chat
  second-job:
    executor:
      name: node/default            
    steps:
      - checkout
      - create-env-vars
      - run: 
          name: "What was my custom environment variable?"
          command: |
            echo ${MY_ENV_VAR}
      - notify-google-chat
  third-job:
    executor:
      name: node/default            
    steps:
      - checkout
      - create-env-vars
      - run: 
          name: "What was my custom environment variable?"
          command: notify-success
      - notify-google-chat
workflows:
    build-and-test:
      jobs:
        - build-and-test
        - second-job
