version: 2.1
orbs:
  node: circleci/node@1.1.6
commands:
  create-env-vars:
    description: "Create en vars"
    steps:
      - run: 
          name: "Setup custom environment variables"
          command: echo 'export MY_ENV_VAR="$(git log --format=%B -n 1 $CIRCLE_SHA1)"' >> $BASH_ENV
  notify-google-chat:
    description: "Notify google chat"
    parameters:
      notify_success:
        default: false
        type: boolean
    steps:
      - run:
          name: Set GIT_COMMIT_MESSAGE
          when: always
          command: echo 'export MY_ENV_VAR="$(git log --format=%B -n 1 $CIRCLE_SHA1)"' >> $BASH_ENV
      - run:
          name: Notify google chat on fail
          when: on_fail
          command: echo Failed $MY_ENV_VAR
      - run:
          name: Notify google chat on success
          when: on_success
          command: echo "Success"
  repo-cache:
    description: "Caching repository"
    steps:
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
      - checkout
      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - ".git"
  dependency-cache:
    description: "Caching dependency"
    parameters:
      test_var:
        type: string
    steps:
      - restore_cache:
          name: "Restoring cache << parameters.test_var >>"
          keys:
            - source-cache-{{ checksum "<< parameters.test_var >>/BreakTimer.js" }}
      - run:
          name: "Install Dependency"
          working_directory: .
          command: npm install
      - save_cache:
          key: source-cache-{{ checksum "<< parameters.test_var >>/BreakTimer.js" }}
          paths:
            - ./node_modules
  test-cache:
    description: "Test"
    steps:
      - restore_cache:
          keys:
            - test-{{ .Branch }}-{{ .Revision }}
      - run:
          name: "Test"
          working_directory: ./assets
          command: ls
      - save_cache:
          key: test-{{ .Branch }}-{{ .Revision }}
          paths:
            - ./assets/icon.png
  test-command1:
    description: "sddf"
    parameters:
      test:
        type: string
    steps:
      - run:
          name: "command 1"
          command : echo << parameters.test >>
  test-command2:
    description: "sddf"
    parameters:
      test:
        type: string
      test2:
        type: string
    steps:
      - test-command1:
          test: << parameters.test >>
      - run:
          name: "command 2"
          command : echo << parameters.test2 >>
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - repo-cache
      - run: 
          name: "What was my custom environment variable?"
          command: echo ${MY_ENV_VAR}
      - notify-google-chat:
          notify_success: true
  second-job:
    executor:
      name: node/default            
    steps:
      - repo-cache
      - dependency-cache:
          test_var: component
      - test-cache
      - notify-google-chat
      - run: 
          name: "What was my custom environment variable?"
          command: |
            echo ${MY_ENV_VAR}
  third-job:
    executor:
      name: node/default
    steps:
      - repo-cache
      - run:
          name: "Install Dependency"
          command: curl -u ${CIRCLE_API_USER_TOKEN} -d 'build_parameters[CIRCLE_JOB]=trigger-job' https://circleci.com/api/v1.1/project/github/Impraveensp/project_timer/tree/${CIRCLE_BRANCH}
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/art-1
            mkdir /tmp/artifacts
      - persist_to_workspace:
          root: /tmp
          paths:
            - artifacts

  fourth-job:
    machine: true
    steps:
      - repo-cache
      - dependency-cache:
          test_var: component
      - test-command2:
          test: "qwe"
          test2: "xyz"
    
  trigger-job:
    machine: true
    steps:
      - run:
          name: "trigger"
          command: |
            echo "It is working"
            if [ true ]; then
            circleci-agent step halt
            fi
      - run:
          name: "trigger"
          command: |
            ls
      - run:
          name: "trigger"
          when: always
          command: |
            echo "Run always"
      

workflows:
    build-and-test:
      jobs:
        # - build-and-test
        # - second-job:
        #     requires:
        #       - build-and-test
        - third-job
        # - fourth-job:
        #     requires:
        #       - build-and-test
