version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export MY_ENV_VAR="$(git log --format=oneline -n 1 $CIRCLE_SHA1)"' >> $BASH_ENV
      - run: 
          name: "What was my custom environment variable?"
          command: |
            echo ${MY_ENV_VAR}
workflows:
    build-and-test:
      jobs:
        - build-and-test
